### ISSUE TITLE
Feature Request: Automatic Timer for Each Question

### ISSUE THREAD

**Issue by RajTangadi** [RajTangadi/quiz-app#1]
### Feature Description
Add an automatic timer to each question. When a user starts a question, a 1-minute timer should begin. If the timer runs out, the app should automatically load the next question without changing the score.

### Feature Requirements
- Display a countdown timer (1 minute) for each question.
- Move to the next question automatically when the timer expires.
- The score should remain unchanged if the timer runs out.

### Potential Benefits
- This feature will encourage users to answer promptly, adding a challenging aspect to the quiz.
- It will improve user engagement by keeping the quiz dynamic.

**Comment by syamjir** [comment]
@RajTangadi ,Assign me
